### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by skylight102** [Jarcho/d2dx#12]
Would it be possible to implement something like HD font? I feel like your motion prediction is superior to D2GL, but the HD font is what keeps me using that. Thanks for your hard work.

**Comment by Jarcho** [comment]
The current motion predictor is a separate module from d2dx. It should take only a relatively simple change to get d2gl using it.

I'm not really planning on adding much feature wise to d2dx.

**Comment by skylight102** [comment]
That’s fair enough, I have very limited knowledge of what would be required, is it done with a hex editor? I’d be greatful if you could show me privately, ***@***.***

Cheers!

On 10 Oct 2023, at 17:26, Jason Newcomb ***@***.***> wrote:

﻿

The current motion predictor is a separate module from d2dx. It should take only a relatively simple change to get d2gl using it.

I'm not really planning on adding much feature wise to d2dx.

**Comment by sandman7920** [comment]
In d2gl disable `vsync`,`foreground_fps`,`background_fps` and `motion_prediction`

```ini
[Screen]
; Vertical synchronization.
; Game fps adapt screen refresh rate (might have input lag).
vsync=false

; Max Foreground FPS (if vsync is on this will be ignored).
; Limit maximum fps when game window is focused(active) (vsync must be disabled).
foreground_fps=false
foreground_fps_value=60

; Max Background FPS.
; Limit maximum fps when game window is in background(inactive).
background_fps=false
background_fps_value=25

[Feature]
; D2DX's Motion Prediction.
motion_prediction=false
```
copy `d2fps.dll` and `d2fps.ini`

in d2fps.ini set `integrity-checks`=**false**

Inject d2fps.dll from Plugy.ini or from other launcher (d2gl.ini doesn't load d2fps.dll, i don't known why)

Plugy.ini
```ini
[GENERAL]
DllToLoad=d2fps
DllToLoad2=BH
```

**Comment by skylight102** [comment]
Thanks Nicholas, legend.

On 10 Oct 2023, at 19:28, Nikolay Zlatev ***@***.***> wrote:

﻿

In d2gl disable vsync,foreground_fps,background_fps and motion_prediction

[Screen]
; Vertical synchronization.
; Game fps adapt screen refresh rate (might have input lag).
vsync=false

; Max Foreground FPS (if vsync is on this will be ignored).
; Limit maximum fps when game window is focused(active) (vsync must be disabled).
foreground_fps=false
foreground_fps_value=60

; Max Background FPS.
; Limit maximum fps when game window is in background(inactive).
background_fps=false
background_fps_value=25

[Feature]
; D2DX's Motion Prediction.
motion_prediction=false

copy d2fps.dll and d2fps.ini

in d2fps.ini set integrity-checks=false

Inject d2fps.dll from Plugy.ini or from other launcher (d2gl.ini doesn't load d2fps.dll, i don't known why)

Plugy.ini

[GENERAL]
DllToLoad=d2fps
DllToLoad2=BH

**Comment by skylight102** [comment]
@Jarcho Have you any idea why it won't load d2fps in the d2gl.ini? I don't use plugy. 

Thanks

**Comment by Jarcho** [comment]
d2gl doesn't call any init function when loading dlls, so d2fps doesn't actually end up hooking into the game.

Missiles will be handled next version. That's an oversight on my part.
