### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by nelsonmenon** [Jarcho/d2dx#13]
hi jarcho, are you still developing this?
i'm using d2fps + d2gl (d2gl for filters and font, d2fps for motion predition, just missing missiles)
are you aware of this pull?
https://github.com/bolrog/d2dx/pull/133
make the scaling floating, not interget, so the windows can be any size 
in my case I use 1068x600, but the 1x screensize is too small em 2x is too big.
is it viable to add this to your fork of d2dx?

**Comment by Jarcho** [comment]
Should be easy enough to pull that in.

**Comment by nelsonmenon** [comment]
Thansk man, I already dropped d2gl and using just d2dx now.
I have a last wish, is it possible to add the fsr filter? (I tried all the filters on d2gl and afaik it's the best and the one that most people are using)

**Comment by Jarcho** [comment]
Open a new issue, otherwise I'll forget about it.
