### ISSUE TITLE
Cinematics are black screen in versions <= 1.02

### ISSUE THREAD

**Issue by buvk** [Jarcho/d2dx#14]
I was testing some older versions of D2 using Cactus, and am launching Game.exe with -3dfx so that I can use d2dx.  I noticed that the cinematics in versions <= 1.02 are black screen.  They seem to work in >= 1.03.  If I do not launch with -3dfx, I can see the cinematics in all versions.

**Comment by Jarcho** [comment]
Fixed on main. Will be in the next release.
