### ISSUE TITLE
Reproducable crash with d2lootfilter

### ISSUE THREAD

**Issue by nelsonmenon** [Jarcho/d2dx#18]
If both D2DX & d2lootfilter are loaded; as soon as I move my cursor over the Defence stat on the character screen, the game crashes. Without fail. Plain SGD2FreeRes does not do this, so I can only imagine it is on D2DX/D2LOOTFILTER side.

reproduced with
d2 1.14d
plugy 14.03
d2lootfilter 0.6b https://github.com/dschu012/d2lootfilter
latest jarcho d2dx

**Comment by Jarcho** [comment]
It's a compatibility issue with d2dx's AA filter. One of d2lootfilter's hooks reaches for data across stack frames and d2dx has a hook in the middle which causes the stack to be shifted.

I can probably shuffle around where d2dx hooks to fix it.

**Comment by Jarcho** [comment]
Fixed with the latest commits.
