### ISSUE TITLE
the "novsync" parameter is invaild

### ISSUE THREAD

**Issue by weili0677** [Jarcho/d2dx#2]
on my 60fps display will up to 150+ fps  and will make the CPU usage too high.

**Comment by Jarcho** [comment]
I don't see what the issue here is. I assume you're saying setting `novsync` is causing the frame rate to go above your monitor's refresh rate, which is exactly what it's supposed to do.

**Comment by weili0677** [comment]
> I don't see what the issue here is. I assume you're saying setting `novsync` is causing the frame rate to go above your monitor's refresh rate, which is exactly what it's supposed to do.

Yes,but I set novsync=false  the FPS also is 150+,however I set the novsync=true or false are also get the FPS 150+.
and I mean the novsync=false is not work anymore

**Comment by Jarcho** [comment]
Ok. Which release are you running? Can you also post the log file as well (`d2dx_log.txt`)?

**Comment by weili0677** [comment]
I build your src use VS2019...and I find the "cross icons" on the minimap also diffrent with bolrog's d2dx 0.99.529 version.

**Comment by weili0677** [comment]
I test your all release version.  only the 12-07 has this issues. before that(such as 12-05 version) is work fine.

**Comment by weili0677** [comment]
> I test your all release version. only the 12-07 has this issues. before that(such as 12-05 version) is work fine.

and The "cross icons" are also fine.

**Comment by weili0677** [comment]
I test your commits,and find out the "[Use FrameLatencyWaitableObject when available](https://github.com/Jarcho/d2dx/commit/5ee2d388e87ccc39cabed8289c9cb73c39894c09)" has "novsync" issues.before this commit is all ok.

**Comment by weili0677** [comment]
I find the reason:
in src/d2dx/RenderContext.cpp  line:101
old code:
_frameLatencyWaitableObjectSupported = false; //  IsFrameLatencyWaitableObjectSupported();
your code:
_frameLatencyWaitableObjectSupported = IsFrameLatencyWaitableObjectSupported();
I recover your code to old. and the "novsync" is work fine.


but the "cross icons" is not good,may be is "AA" stuff?

**Comment by weili0677** [comment]
the "cross icons" issues is start with commit "Use sub-pixel precision for motion prediction".
can you fix it?^_^

**Comment by weili0677** [comment]
I fix the "cross icons" issues too.Thank you for your good modify D2DX. Thank you.
and the my edit code is in D2DXContext.cpp line 745-748,and change to:
```
		vertex0.SetPosition((int32_t)(d2Vertex1->x + widening.x), (int32_t)(d2Vertex1->y - widening.y));
		vertex1.SetPosition((int32_t)(d2Vertex0->x + widening.x), (int32_t)(d2Vertex0->y - widening.y));
		vertex2.SetPosition((int32_t)(d2Vertex1->x - widening.x), (int32_t)(d2Vertex1->y + widening.y));
		vertex3.SetPosition((int32_t)(d2Vertex0->x - widening.x), (int32_t)(d2Vertex0->y + widening.y));
```

**Comment by Jarcho** [comment]
The cross icons were drawn incorrectly before that. What's currently drawn matches what 3dfx cards would draw.

**Comment by weili0677** [comment]
> The cross icons were drawn incorrectly before that. What's currently drawn matches what 3dfx cards would draw.

OK,Thank you.but The cross icons with before version seem like cross and currently version is not like^^.

**Comment by Jarcho** [comment]
I assume the log you posted is from a version you compiled yourself? Seems like `FrameLatencyWaitableObject` isn't working for you for some reason.

**Comment by Jarcho** [comment]
Latest changes should fix the vsync issue. I won't be reverting the changes to the line drawing, the old version was just drawing incorrect lines. I'll look into drawing anti-aliased lines at some point and see how those look.

**Comment by weili0677** [comment]
> Latest changes should fix the vsync issue. I won't be reverting the changes to the line drawing, the old version was just drawing incorrect lines. I'll look into drawing anti-aliased lines at some point and see how those look.

OK，thank you.again.have a good time.
