### ISSUE TITLE
Config file d2dx-defaults.cfg included with d2dx-2023-11-16 is outdated ?

### ISSUE THREAD

**Issue by eleriaqueen** [Jarcho/d2dx#21]
Hi, sorry for bothering you.
It looks like you added fractional window scaling support on 2023-11-13 but bundled config file of d2dx-2023-11-16 (the latest) still mentions scale being an integer.

Thank you for improving and giving polish to D2DX.

**Comment by Jarcho** [comment]
Looks like I included the wrong config with the release. The current commit does have it worded correctly.
