### ISSUE TITLE
A bug with PD2 mod

### ISSUE THREAD

**Issue by weili0677** [Jarcho/d2dx#23]
When open the PD2 mod's "Quick Cast",set and press the Skill short key,the skill will cast never stop until press other Key or mouse click.
For example：
The Barbarian's Skill "Howl" of Warcries
When I Set F7 for it
and go outside open the PD2 mod's "Quick Cast" and press the F7,and it's will cast Howl but never stop until MP is 0 or press other Key or mouse click.

It's seem like keydown is trigger but keyup is not trigger.

**Comment by weili0677** [comment]
This is the test video:
https://github.com/Jarcho/d2dx/assets/2888483/260e7c10-f7d3-4e5b-bbad-a467f9fc037d

**Comment by Jarcho** [comment]
Incompatibility with d2fps. ProjectD2 relies on the rendering code running immediately after the game state updates (this is dumb and they shouldn't do this). As a workaround you can set the frame limiter higher than you can render (e.g. 1000).

A proper fix would need to be done on their side.

**Comment by weili0677** [comment]
Thank you.and where Can I set the frame limiter? d2fps.ini？

**Comment by Jarcho** [comment]
That can be set in d2fps.ini or on the command line.

**Comment by weili0677** [comment]
> That can be set in d2fps.ini or on the command line.

ok，I set novsync=false in the d2dx.cfg also can fix this issues.

**Comment by Jarcho** [comment]
>I set novsync=false in the d2dx.cfg also can fix this issues.
No. Changing vsync won't work.

> and which args in d2fps.ini? fps=?
Yes. You want the `fps` setting in `d2fps.ini`.

**Comment by weili0677** [comment]
> > I set novsync=false in the d2dx.cfg also can fix this issues.
> 
> No. Changing vsync won't work.
> 
> > and which args in d2fps.ini? fps=?
> 
> Yes. You want the `fps` setting in `d2fps.ini`.

Thank you,I set fps=1000,It is not never stop casting for now.
