### ISSUE TITLE
Hi,Jarcho.0.103.3 have game windows issues with single monitor.

### ISSUE THREAD

**Issue by weili0677** [Jarcho/d2dx#28]
I have a small resolution monitor(1920x1080,DPI=125%).
and I set 2x Scales with window.
when I start game and the game window's height will more then (screen height - taskbar height),It's mean the taskbar will block the bottom of the game window.
and  when into the game,the top of window also not top near the screen top.

**Comment by Jarcho** [comment]
Fixed in 0.103.4.
