### ISSUE TITLE
Crash when switching between 640x480 and 800x600

### ISSUE THREAD

**Issue by wasdwdsa** [Jarcho/d2dx#30]
The game sometimes crashes when I switching the resolution in the video options. (not always)

The report under BlizzardError folder:
[2024-08-17 12.43.45.zip](https://github.com/user-attachments/files/16643428/2024-08-17.12.43.45.zip)

Enviornment: Windows 11 Home 21H2
Game verion: 1.14d + d2dx 0.103.4. No other mods.
Configuration: noresmod was set to true, others are default.

**Comment by wasdwdsa** [comment]
Seems not d2dx issue. Reproducible without d2dx.

**Comment by Jarcho** [comment]
Looks like the lock for the sprite cache got corrupted somehow. I don't have 1.14 reversed well enough to actually debug that.
