### ISSUE TITLE
D2DX and Battle.net

### ISSUE THREAD

**Issue by 2mg** [Jarcho/d2dx#32]
Is it safe to use D2DX on Battle.net wihout SGDFreeRes?

**Comment by Jarcho** [comment]
I would assume no. If you run with `noresmod`, `nofpsmod` and `noaa` then no game code will be patched.

**Comment by 2mg** [comment]
> I would assume no. If you run with `noresmod`, `nofpsmod` and `noaa` then no game code will be patched.

Thanks, guess in that case it's works as a modern wrapper - will render a low rez to a fullscreen image, nothing else, but still good to get old D2 running on modern systems?
