### ISSUE TITLE
D2DX with ResMod: incorrect mouse rock area in windowed mode

### ISSUE THREAD

**Issue by qqkookie** [Jarcho/d2dx#4]
Current working version of D2DX by Jarcho seems to have some problem with internal ResMod. 
The D2DX without internal ResMod works great and have no problem.
But when compiled with Resmod included and D2 is launched 
in Windowed mode with "-w -3dfx", The mouse lock area works  incorrectly.
. 
When user launches D2 client, it starts with windowed mode, and the "mouse lock" area works correctly. 
And when player enters new game session by selecting Dia character, 
the game window expands to so-called "windowed full screen" mode 
(with top title bar and explorer task bar)

But the left side of "mouse lock area" remains the same "launch window area boundary". 
Up and down and right area mouse lock area boundary works correctly. Only left is incorrect. 
I use 1024\*768 4:3 D2 resolution and real window desktop resolution is 2560\*1440. 
Old version by @bolrog/d2dx with internal resmod works correctly without such problem

**Comment by Jarcho** [comment]
Can you test the latest version and see if that fixes the issue?

**Comment by qqkookie** [comment]
Not fixed.  
If I set `noclipcursor=true` in `[optoin] section of `d2dx.cfg` config file and launch the game in window mode with `Game.exe -3dx -w` command line options , mouse is locked correctly in game title and character selection screen. But when I enter new game session, the game window is maximized and mouse lock area is expanded too. But **LEFT** boundary of mouse lock area is remained same as initial game title window size. 
When and only when `noclipcursor=false` works correctly.

**Comment by Jarcho** [comment]
Fixed in v0.100.1

**Comment by qqkookie** [comment]
Tested V0.100.1. The mouse lock works, but incorrectly.  When moving mouse to right edge of D2 window, the mouse cursor does not stop at right edge, but it jumps abruptly to middle of window on same x -axis. This is not correct behavior. Mouse should stop at right edge. Only right edge shows such "jumping" behavior. Mouse on left, top, bottom edges work correctly.

**Comment by Jarcho** [comment]
That is a weird d2 bug that would normally ever be triggered, Fixed in v0.100.2.
